package netfilter

import (
	"net"
	"regexp"
	"strconv"
	"strings"
)

var (
	vethRegex = regexp.MustCompile(`veth(\d+)i`)
)

// IptablesEvent represents a parsed packet event from iptables/netfilter kernel logs.
type IptablesEvent struct {
	VMID           int    `json:"vmid"`
	Direction      string `json:"direction"` // "IN" or "OUT"
	Proto          string `json:"proto"`     // "TCP", "UDP", "ICMP", etc.
	Src            string `json:"src"`
	Dst            string `json:"dst"`
	SPT            int    `json:"spt"`
	DPT            int    `json:"dpt"`
	IsLocalProcess bool   `json:"is_local_process"`
	Interface      string `json:"interface,omitempty"`
	RawLine        string `json:"raw_line,omitempty"`
}

// IsPrivateIP checks whether the given IP string is a private, loopback, link-local, or CGNAT IP.
func IsPrivateIP(ipStr string) bool {
	ipStr = strings.TrimSpace(ipStr)
	if ipStr == "" || ipStr == "127.0.0.1" || ipStr == "::1" || ipStr == "localhost" {
		return true
	}

	parsedIP := net.ParseIP(ipStr)
	if parsedIP == nil {
		return false
	}

	if parsedIP.IsLoopback() || parsedIP.IsLinkLocalUnicast() || parsedIP.IsLinkLocalMulticast() || parsedIP.IsPrivate() {
		return true
	}

	// Check CGNAT: 100.64.0.0/10
	if v4 := parsedIP.To4(); v4 != nil {
		if v4[0] == 100 && (v4[1]&0xC0) == 64 {
			return true
		}
	}

	return false
}

// IsIgnoredBroadcastOrMulticast checks if an IP is a broadcast, multicast, or invalid destination.
func IsIgnoredBroadcastOrMulticast(ipStr string) bool {
	if ipStr == "255.255.255.255" || strings.HasSuffix(ipStr, ".255") {
		return true
	}

	parsedIP := net.ParseIP(ipStr)
	if parsedIP == nil {
		return false
	}

	if parsedIP.IsMulticast() {
		return true
	}

	if v4 := parsedIP.To4(); v4 != nil {
		if v4[0] >= 224 && v4[0] <= 239 {
			return true
		}
	}

	return false
}

// ParseIptablesLine parses a kernel log line generated by iptables/nftables LOG targets.
// Supports LXC_CONN, LXC_CONN_OUT, HOST_CONN, HOST_CONN_OUT, LXC_VPN_LOCAL_OUT, REMOTE_CONN, REMOTE_CONN_OUT.
func ParseIptablesLine(line string, vpnVMID int) *IptablesEvent {
	clean := strings.TrimSpace(line)
	if clean == "" {
		return nil
	}

	hasLXCConn := strings.Contains(clean, "LXC_CONN:")
	hasLXCConnOut := strings.Contains(clean, "LXC_CONN_OUT:")
	hasHostConn := strings.Contains(clean, "HOST_CONN:")
	hasHostConnOut := strings.Contains(clean, "HOST_CONN_OUT:")
	hasVPNLocalOut := strings.Contains(clean, "LXC_VPN_LOCAL_OUT:")
	hasRemoteConn := strings.Contains(clean, "REMOTE_CONN:")
	hasRemoteConnOut := strings.Contains(clean, "REMOTE_CONN_OUT:")

	if !hasLXCConn && !hasLXCConnOut && !hasHostConn && !hasHostConnOut && !hasVPNLocalOut && !hasRemoteConn && !hasRemoteConnOut {
		return nil
	}

	direction := "IN"
	if hasLXCConnOut || hasHostConnOut || hasVPNLocalOut || hasRemoteConnOut {
		direction = "OUT"
	}

	// Parse key=value pairs
	parts := strings.Fields(clean)
	kv := make(map[string]string)
	for _, p := range parts {
		if idx := strings.IndexByte(p, '='); idx > 0 {
			k := p[:idx]
			v := p[idx+1:]
			kv[k] = v
		}
	}

	// Determine VMID
	vmid := 0
	if !hasHostConn && !hasHostConnOut && !hasRemoteConn && !hasRemoteConnOut {
		if hasVPNLocalOut {
			vmid = vpnVMID
		} else {
			vmidFound := -1
			for _, ifaceKey := range []string{"PHYSIN", "PHYSOUT", "IN", "OUT"} {
				if ifaceVal, ok := kv[ifaceKey]; ok && ifaceVal != "" {
					if m := vethRegex.FindStringSubmatch(ifaceVal); len(m) >= 2 {
						if parsedVMID, err := strconv.Atoi(m[1]); err == nil {
							vmidFound = parsedVMID
							break
						}
					}
				}
			}
			if vmidFound == -1 {
				return nil
			}
			vmid = vmidFound
		}
	}

	dst := kv["DST"]
	if dst == "" {
		dst = "UNKNOWN"
	}

	if IsIgnoredBroadcastOrMulticast(dst) {
		return nil
	}

	spt, _ := strconv.Atoi(kv["SPT"])
	dpt, _ := strconv.Atoi(kv["DPT"])

	src := kv["SRC"]
	if src == "" {
		src = "UNKNOWN"
	}

	proto := kv["PROTO"]
	if proto == "" {
		proto = "UNKNOWN"
	}

	isLocalProcess := hasVPNLocalOut

	iface := kv["IN"]
	if direction == "OUT" && kv["OUT"] != "" {
		iface = kv["OUT"]
	}

	return &IptablesEvent{
		VMID:           vmid,
		Direction:      direction,
		Proto:          proto,
		Src:            src,
		Dst:            dst,
		SPT:            spt,
		DPT:            dpt,
		IsLocalProcess: isLocalProcess,
		Interface:      iface,
		RawLine:        clean,
	}
}
